services:
  - type: worker
    name: telegram-voice-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7583083761:AAEc4R2q7qVm0RQKzKRaTPAOXpT7saXcn3Y
      - key: GEMINI_API_KEY
        value: AIzaSyBr1mI21WL76WSKn0zpVRmNCkSuKL9TJvw
