services:
  - type: worker
    name: telegram-voice-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 
      - key: GEMINI_API_KEY
        value: 
